name: phasiHunter
channels:
- conda-forge
- bioconda
dependencies:
- bedtools=2.31.0
- biopython=1.81
- bowtie=1.3.1
- cutadapt=4.5
- fastqc=0.12.1
- trim-galore=0.6.10
- dnapi=1.1
- pyyaml=6.0.1
- sympy=1.12
- matplotlib=3.8.2
- fasta3=36.3.8
